# Generated by Django 5.2.7 on 2025-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profiles', '0004_profileclick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day'], 'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Horario de cierre (entre 6:30 AM y 10:00 PM, en intervalos de 30 minutos)', null=True, verbose_name='Hora de cierre'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Horario de inicio (entre 6:00 AM y 9:30 PM, en intervalos de 30 minutos)', null=True, verbose_name='Hora de inicio'),
        ),
    ]
